(() => {
  const API_URL="https://avani-ai-q7mq.onrender.com";
  const $=id=>document.getElementById(id),qs=s=>document.querySelector(s);
  const toast=t=>{const e=$("toast");if(!e)return;e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)};

  function addCSS(){if($("avani-mobile-v7"))return;const s=document.createElement("style");s.id="avani-mobile-v7";s.textContent=`
  .chat-tools{max-width:900px;margin:0 auto 8px;display:flex;gap:7px;justify-content:flex-end}.chat-tools button{border:1px solid #3b465c;background:#0e1522;color:#aeb8c8;border-radius:10px;padding:7px 10px;font-size:10px}
  .attachment-preview{max-width:900px;margin:0 auto 8px;display:none;align-items:center;gap:9px;padding:8px 10px;border:1px solid #29354b;background:#0d1421;border-radius:12px}.attachment-preview img{width:42px;height:42px;border-radius:9px;object-fit:cover}.attachment-preview .meta{min-width:0;flex:1}.attachment-preview b,.attachment-preview small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment-preview small{color:#78849a;font-size:9px}.attachment-preview button{border:0;background:transparent;color:#9aa6ba;font-size:18px;padding:5px 8px}
  @media(max-width:760px){html,body,.app,.main{width:100%;height:100dvh;overflow:hidden}.sidebar{position:fixed;left:-285px;top:0;bottom:0;height:100dvh;transition:left .22s}.sidebar.open{left:0}.topbar{height:60px;padding:0 10px}.chat-scroll{height:100%;padding:16px 9px 180px}.message{max-width:100%;margin-bottom:11px}.bubble{max-width:calc(100vw - 72px);font-size:13px;padding:10px 12px;overflow-wrap:anywhere}.composer-wrap{position:fixed;left:0;right:0;bottom:0;padding:7px 8px calc(8px + env(safe-area-inset-bottom));background:linear-gradient(180deg,#070a1200,#070a12 18%,#070a12)}.composer{width:100%;border-radius:14px}.composer textarea{font-size:15px}.quick{margin-bottom:6px}.quick button{font-size:9px;padding:6px 9px}.section-head{padding:20px 14px 15px}.map-layout,.coding-grid,.memory-grid,.vision-work{grid-template-columns:1fr;padding-left:14px;padding-right:14px}.dashboard-grid,.security-grid{grid-template-columns:1fr;padding-left:14px;padding-right:14px}.studio-grid{grid-template-columns:1fr;padding:0 14px}.tool-hub{grid-template-columns:repeat(2,1fr);padding:0 14px}.tool-work{padding:12px 14px;display:grid;grid-template-columns:1fr}.file-list{padding-left:14px;padding-right:14px}.file-drop,.upload-zone{margin-left:14px;margin-right:14px}.voice-card{margin:15px 14px;padding:25px 16px}.voice-actions{flex-direction:column}}
  `;document.head.appendChild(s)}

  function controls(){const w=qs(".composer-wrap");if(!w)return;if(!$("clearChatButton")){const t=document.createElement("div");t.className="chat-tools";t.innerHTML=`<button id="clearChatButton" type="button">🧹 Clear chat</button><button id="clearAllChatsButton" type="button">🗑️ Clear all</button>`;w.insertBefore(t,w.firstChild);$("clearChatButton").onclick=clearChat;$("clearAllChatsButton").onclick=clearAll}
    if(!$("attachmentPreview")){const p=document.createElement("div");p.className="attachment-preview";p.id="attachmentPreview";p.innerHTML=`<img id="attachmentThumb" alt="Selected image"><div class="meta"><b id="attachmentName">Image ready</b><small id="attachmentHint">Ready for Vision</small></div><button id="analyzeAttachment" type="button">Analyze</button><button id="removeAttachment" type="button">×</button>`;w.insertBefore(p,w.querySelector(".composer"));$("analyzeAttachment").onclick=()=>{const f=$("fileInput")?.files?.[0];f?vision(f):toast("Choose an image first")};$("removeAttachment").onclick=clearAttachment}}
  function clearChat(){if(!confirm("Clear all messages from this chat?"))return;const c=typeof window.currentChat==="function"?window.currentChat():null;if(!c)return toast("No chat to clear");c.messages=[];c.title="New Chat";if(typeof window.saveChats==="function")window.saveChats();else localStorage.setItem("avaniChats",JSON.stringify(JSON.parse(localStorage.getItem("avaniChats")||"[]").map(x=>x.id===c.id?c:x)));window.renderChat?.();window.renderHistory?.();toast("Current chat cleared")}
  function clearAll(){if(!confirm("Delete all saved chats? This cannot be undone."))return;localStorage.removeItem("avaniChats");localStorage.removeItem("avaniCurrentChat");location.reload()}
  function resize(){const e=$("userInput");if(e){e.style.height="auto";e.style.height=Math.min(e.scrollHeight,150)+"px"}}

  async function stableSend(){const e=$("userInput"),b=$("sendButton");if(!e||!b||b.disabled)return;const text=e.value.trim();if(!text)return;if(window.requireUser&&!window.requireUser())return;if(!window.currentChat?.()&&window.newChat)window.newChat();e.value="";resize();e.blur();b.disabled=true;b.setAttribute("aria-busy","true");window.renderMessage?.(text,"user",window.userProfile?.photo);const wait=window.renderMessage?.("Avani is thinking…","ai",null,false);const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),40000);try{const h=window.historyForAI?.().slice(0,-1)||[];const r=await fetch(`${API_URL}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({message:text,history:h}),signal:ac.signal,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Server error ${r.status}`);wait?.remove();window.renderMessage?.(d.reply||"I couldn't generate a reply.","ai");window.speak?.(d.reply||"")}catch(err){wait?.remove();window.renderMessage?.(err.name==="AbortError"?"Avani took too long to respond. Please try again.":`I couldn't connect right now. ${err.message}`,"ai");toast("AI connection failed")}finally{clearTimeout(timer);b.disabled=false;b.removeAttribute("aria-busy");setTimeout(()=>e.focus(),50)}}

  function clearAttachment(){const p=$("attachmentPreview"),f=$("fileInput");if(p)p.style.display="none";if(f)f.value="";window.avaniPendingImage=null}
  function selectImage(file){const p=$("attachmentPreview"),img=$("attachmentThumb");if(!p||!img)return;p.style.display="flex";$("attachmentName").textContent=file.name;$("attachmentHint").textContent=`${Math.round(file.size/1024)} KB · ready for Vision`;const r=new FileReader();r.onload=()=>{img.src=r.result;window.avaniPendingImage=r.result};r.readAsDataURL(file)}
  async function vision(file){if(!file||file.size>8*1024*1024)return toast("Image must be under 8MB");const r=new FileReader();r.onload=async()=>{try{const x=await fetch(`${API_URL}/api/vision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:r.result,question:"Analyze this uploaded image. Describe visible content, read useful text when possible, identify important details, and suggest next steps."}),cache:"no-store"}),d=await x.json().catch(()=>({}));if(!x.ok)throw Error(d.error||`Vision error ${x.status}`);window.showView?.("chat");window.renderMessage?.(`Image analysis:\n\n${d.reply||"No analysis returned."}`,"ai");clearAttachment()}catch(e){toast(`Image analysis failed: ${e.message}`)}};r.readAsDataURL(file)}
  function patchFile(){const f=$("fileInput");if(!f)return;f.onchange=e=>{const files=[...e.target.files].slice(0,8);const image=files.find(x=>x.type.startsWith("image/")||/\.(png|jpe?g|webp|gif)$/i.test(x.name));if(image){selectImage(image);return}window.showView?.("files");const target=$("toolFileInput");if(target){try{const dt=new DataTransfer();files.forEach(x=>dt.items.add(x));target.files=dt.files;target.dispatchEvent(new Event("change",{bubbles:true}))}catch{toast("Open File Intelligence to choose files")}}}}
  function patch(){addCSS();controls();patchFile();const input=$("userInput"),send=$("sendButton");if(input){input.oninput=resize;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.stopImmediatePropagation();stableSend()}}}if(send)send.onclick=e=>{e.preventDefault();stableSend()};const mic=$("micButton");if(mic)mic.onclick=()=>{$("voiceStart")?.click()};}
  document.addEventListener("DOMContentLoaded",()=>{patch();setTimeout(patch,300);setTimeout(patch,1000)})
})();