const input=document.getElementById("userInput");
const messages=document.getElementById("messages");
const API_URL="https://avani-ai-q7mq.onrender.com/api/chat";
let chats=JSON.parse(localStorage.getItem("avaniChats"))||[];
let currentChatId=localStorage.getItem("avaniCurrentChat");
let memory=JSON.parse(localStorage.getItem("avaniMemory"))||[];
let voiceReplies=localStorage.getItem("avaniVoice")==="true";
let quickPrompts=localStorage.getItem("avaniQuickPrompts")!=="false";
let recognition=null;
let userProfile=JSON.parse(localStorage.getItem("avaniUserProfile"))||null;

const $=id=>document.getElementById(id);
function saveProfile(){localStorage.setItem("avaniUserProfile",JSON.stringify(userProfile))}
function escapeHTML(text){const d=document.createElement("div");d.textContent=String(text??"");return d.innerHTML}
function saveChats(){localStorage.setItem("avaniChats",JSON.stringify(chats));localStorage.setItem("avaniCurrentChat",currentChatId||"")}
function getCurrentChat(){return chats.find(c=>c.id===currentChatId)}
function welcomeHTML(){return `<div class="welcome"><div class="welcome-avatar">A</div><span class="welcome-badge">✦ NEXT-GEN AI ASSISTANT</span><h1>Hi, I'm Avani 👋</h1><p>Ask questions, write, code, plan projects, explore ideas and learn step by step.</p></div>`}
function createNewChat(){const chat={id:Date.now().toString(),title:"New Chat",messages:[]};chats.unshift(chat);currentChatId=chat.id;saveChats();renderChat();renderChatHistory();input.focus();closeSidebar()}
function renderChat(){const chat=getCurrentChat();messages.innerHTML=chat&&chat.messages.length?"":welcomeHTML();if(chat)chat.messages.forEach(m=>addMessage(m.text,m.sender,false,m.avatar));messages.scrollTop=messages.scrollHeight}
function addMessage(text,sender="ai",save=true,avatar=null){const message=document.createElement("div");message.className=`message ${sender}`;const content=document.createElement("div");content.className="message-content";const avatarEl=document.createElement("div");avatarEl.className="message-avatar";avatarEl.textContent=sender==="user"?(avatar?"":"👤"):"A";if(sender==="user"&&avatar){avatarEl.style.backgroundImage=`url(${avatar})`;avatarEl.textContent=""}message.append(avatarEl,content);content.textContent=String(text??"");messages.appendChild(message);messages.scrollTop=messages.scrollHeight;if(save){const chat=getCurrentChat();if(!chat)return;chat.messages.push({text:String(text??""),sender,time:new Date().toISOString(),avatar});if(sender==="user"&&chat.title==="New Chat")chat.title=text.length>32?text.slice(0,32)+"…":text;saveChats();renderChatHistory()}return message}
function renderChatHistory(){const list=$("historyList");if(!list)return;list.innerHTML="";chats.slice(0,12).forEach(chat=>{const item=document.createElement("div");item.className=`history-item ${chat.id===currentChatId?"active":""}`;item.innerHTML=`<span>💬</span><span class="history-name">${escapeHTML(chat.title)}</span><button class="delete-chat" title="Delete chat">×</button>`;item.onclick=e=>{if(e.target.closest(".delete-chat")){deleteChat(chat.id);return}currentChatId=chat.id;saveChats();renderChat();renderChatHistory();closeSidebar()};list.appendChild(item)})}
function deleteChat(id){if(!confirm("Delete this chat?"))return;chats=chats.filter(c=>c.id!==id);if(currentChatId===id)currentChatId=chats[0]?.id||null;saveChats();renderChat();renderChatHistory()}
function detectMemory(text){const patterns=[/my name is\s+(.+)/i,/mera naam\s+(.+)/i,/i like\s+(.+)/i,/mujhe pasand\s+(.+)/i,/my favorite\s+(.+)/i,/mera favourite\s+(.+)/i];for(const p of patterns){const m=text.match(p);if(m){const value=m[1].trim().replace(/[.!?]+$/,'');if(value&&value.length<100&&!memory.includes(value)){memory.unshift(value);memory=memory.slice(0,20);localStorage.setItem("avaniMemory",JSON.stringify(memory))}}}}
function showModal(id){$(id).hidden=false}
function closeModal(id){$(id).hidden=true}
function renderMemory(){const list=$("memoryList");if(!memory.length){list.innerHTML='<div class="empty-memory">No saved memories yet.</div>';return}list.innerHTML=memory.map(x=>`<div class="memory-item">🧠 ${escapeHTML(x)}</div>`).join("")}
function speak(text){if(!voiceReplies||!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();const female=voices.find(v=>/female|zira|samantha|google uk english female|google us english/i.test(`${v.name} ${v.voiceURI}`))||voices.find(v=>/^en|^hi/i.test(v.lang));if(female)u.voice=female;u.rate=.96;u.pitch=1.08;speechSynthesis.speak(u)}
function setupSpeech(){if(!("webkitSpeechRecognition"in window||"SpeechRecognition"in window))return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new SR();recognition.lang="hi-IN";recognition.interimResults=false;recognition.onstart=()=>$("micButton").classList.add("recording");recognition.onend=()=>$("micButton").classList.remove("recording");recognition.onerror=()=>$("micButton").classList.remove("recording");recognition.onresult=e=>{input.value=e.results[0][0].transcript;resizeInput();input.focus()}}
function buildHistory(){const chat=getCurrentChat();if(!chat)return[];return chat.messages.slice(-24).map(m=>({role:m.sender==="user"?"user":"assistant",content:String(m.text||"")}))}
async function sendMessage(){const text=input.value.trim();if(!text)return;if(!userProfile){openAuth();return}if(!getCurrentChat())createNewChat();const history=buildHistory();addMessage(text,"user",true,userProfile.photo);input.value="";resizeInput();input.disabled=true;$("sendButton").disabled=true;const thinking=addMessage("Avani is thinking…","ai",false);try{const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history})});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||"Server error");thinking.remove();const reply=data.reply||data.message||"I couldn't generate a reply.";addMessage(reply,"ai");detectMemory(text);speak(reply)}catch(error){thinking.remove();addMessage(`Connection issue: ${error.message||"Backend unavailable"}`,"ai")}finally{input.disabled=false;$("sendButton").disabled=false;input.focus()}}
function resizeInput(){input.style.height="auto";input.style.height=Math.min(input.scrollHeight,150)+"px"}
function openAuth(){showModal("authModal");setTimeout(()=>$("profileName")?.focus(),30)}
function saveUserProfile(){const name=$("profileName").value.trim();const photo=$("profilePhoto").files[0];if(!name){$("profileName").focus();return}const finish=data=>{userProfile={name,photo:data||userProfile?.photo||null};saveProfile();closeModal("authModal");updateProfileUI();if(!getCurrentChat())createNewChat()};if(photo){if(photo.size>4*1024*1024){alert("Please choose a photo under 4MB.");return}const r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(photo)}else finish(null)}
function updateProfileUI(){const nameEl=$("userName"),avatar=$("userAvatar");if(!nameEl||!avatar)return;if(userProfile){nameEl.textContent=userProfile.name;avatar.textContent="";avatar.style.backgroundImage=userProfile.photo?`url(${userProfile.photo})`:"none";if(!userProfile.photo)avatar.textContent=userProfile.name.charAt(0).toUpperCase()}else{nameEl.textContent="Guest";avatar.style.backgroundImage="none";avatar.textContent="?"}}
function logout(){userProfile=null;localStorage.removeItem("avaniUserProfile");updateProfileUI();openAuth()}
function closeSidebar(){$("sidebar")?.classList.remove("open");$("mobileOverlay")?.classList.remove("show")}
function toggleTheme(enabled){document.body.classList.toggle("light-mode",enabled);localStorage.setItem("avaniLight",enabled?"true":"false")}
function applySettings(){const light=localStorage.getItem("avaniLight")==="true";toggleTheme(light);$("themeToggle").checked=!light;$("quickPromptToggle").checked=quickPrompts;$("voiceSettingToggle").checked=voiceReplies;$("quickPrompts").style.display=quickPrompts?"flex":"none"}

document.addEventListener("DOMContentLoaded",()=>{renderChat();renderChatHistory();updateProfileUI();setupSpeech();applySettings();if(!userProfile)setTimeout(openAuth,250);$("newChatButton").onclick=createNewChat;$("sendButton").onclick=sendMessage;$("attachButton").onclick=()=>$("fileInput").click();$("fileInput").onchange=()=>{const f=$("fileInput").files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{input.value=`Please analyze this file:\n\n${String(reader.result).slice(0,30000)}`;resizeInput();input.focus()};reader.readAsText(f)};$("micButton").onclick=()=>{if(recognition){try{recognition.start()}catch{}}else alert("Voice input is not supported in this browser.")};$("voiceToggle").onclick=()=>{voiceReplies=!voiceReplies;localStorage.setItem("avaniVoice",voiceReplies);$("voiceToggle").textContent=voiceReplies?"🔊":"🔇";if(voiceReplies)speak("Voice replies are on.")};$("voiceToggle").textContent=voiceReplies?"🔊":"🔇";$("memoryNav").onclick=()=>{renderMemory();showModal("memoryModal")};$("settingsNav").onclick=()=>{applySettings();showModal("settingsModal")};$("studioNav").onclick=()=>showModal("studioModal");$("chatNav").onclick=()=>closeSidebar();$("sidebarToggle").onclick=()=>{$("sidebar").classList.add("open");$("mobileOverlay").classList.add("show")};$("mobileOverlay").onclick=closeSidebar;$("clearChatButton").onclick=()=>{const c=getCurrentChat();if(c){c.messages=[];c.title="New Chat";saveChats();renderChat();renderChatHistory()}};$("clearMemoryButton").onclick=()=>{memory=[];localStorage.removeItem("avaniMemory");renderMemory()};$("saveProfileButton").onclick=saveUserProfile;$("logoutButton").onclick=logout;$("themeToggle").onchange=e=>toggleTheme(!e.target.checked);$("quickPromptToggle").onchange=e=>{quickPrompts=e.target.checked;localStorage.setItem("avaniQuickPrompts",quickPrompts);applySettings()};$("voiceSettingToggle").onchange=e=>{voiceReplies=e.target.checked;localStorage.setItem("avaniVoice",voiceReplies);$("voiceToggle").textContent=voiceReplies?"🔊":"🔇"};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.hidden=true}));document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;resizeInput();input.focus()});input.addEventListener("input",resizeInput);input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});$("profilePhoto").onchange=()=>{const f=$("profilePhoto").files[0];if(f&&f.size>4*1024*1024)alert("Please choose a photo under 4MB.")}});
